[cmo]
cmo_install_dir = C:/Program Files (x86)/Steam/steamapps/common/Command Modern Operations
; optional override:
; db_dir = C:/Program Files (x86)/Steam/steamapps/common/Command Modern Operations/DB
